//
//  ModelTests+AutogeneratedMock.swift
//  TestingPlaygroundTests
//
//  Created by Дмитрий Тримонов on 18.07.2021.
//

import XCTest
import SwiftyMocky
@testable import TestingPlayground

class GeneratedMockModelTests: XCTestCase {

    func testFetchPerformsLoggingWithInfoScope() {
        // Arrange
        let loggerMock = ILoggerMock()
        let sut = Model(logger: loggerMock)
        
        // Act
        sut.fetch()
        
        // Assert
        Verify(loggerMock, 1, .log(.any, scope: .value(.info)))
    }

}
